### ISSUE TITLE
 "dependencies" has dependency "shortid" with range "^2.2.13" that collides with a dependency in "devDependencies" of the same name with version "^2.2.8"

### ISSUE THREAD

**Issue by qhj1990** [wjkang/d2-admin-server#1]
"dependencies" has dependency "shortid" with range "^2.2.13" that collides with a dependency in "devDependencies" of the same name with version "^2.2.8".
package.json 中的 dependencies 和 devDependencies均有一个依赖叫 shorid。

**Comment by ghost** [comment]
yarn run v1.13.0
warning package.json: No license field
warning package.json: "dependencies" has dependency "shortid" with range "^2.2.13" that collides with a dependency in "devDependencies" of the same name with version "^2.2.8"
$ gulp nodemon
gulp[13048]: ../src/node_contextify.cc:631:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x100060313 node::Abort() [/usr/local/Cellar/node/11.10.1/bin/node]
 2: 0x100060250 node::PrintErrorString(char const*, ...) [/usr/local/Cellar/node/11.10.1/bin/node]
 3: 0x10005cafe node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/Cellar/node/11.10.1/bin/node]
 4: 0x1001e0438 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/Cellar/node/11.10.1/bin/node]
 5: 0x1001df7fc v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/Cellar/node/11.10.1/bin/node]
 6: 0x1001df295 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/Cellar/node/11.10.1/bin/node]
 7: 0x3f6f6294fc7d 
 8: 0x3f6f62909e66 
 9: 0x3f6f6298c260 
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ghost** [comment]
是不是node版本太高了

**Comment by ghost** [comment]
好像我弄好了 `npm install -g n` `n lts` `node -v` `v10.15.2` `yarn` `yarn dev`

**Comment by ghost** [comment]
/usr/local/bin/node /usr/local/Cellar/yarn/1.13.0/libexec/bin/yarn.js run dev
yarn run v1.13.0
warning package.json: No license field
$ gulp
[21:55:07] Using gulpfile ~/WebstormProjects/d2-admin-server/gulpfile.js
[21:55:07] Starting 'ESlint'...
- Total Results: 0
- Total Warnings: 0
- Total Errors: 0
[21:55:07] Finished 'ESlint' after 534 ms
[21:55:07] Starting 'ESlint_nodemon'...
[21:55:07] Finished 'ESlint_nodemon' after 36 ms
[21:55:07] Starting 'default'...
[21:55:07] Finished 'default' after 44 μs
[21:55:07] [nodemon] 1.18.10
[21:55:07] [nodemon] to restart at any time, enter `rs`
[21:55:07] [nodemon] ignoring: build/*.js dist/*.js nodemon.json ./.git/**/* node_modules/**/node_modules gulpfile.js
[21:55:07] [nodemon] watching: *.*
[21:55:07] [nodemon] watching extensions: js,json
[21:55:07] [nodemon] starting `node build/dev-server.js`
[21:55:07] [nodemon] spawning
[21:55:07] [nodemon] child pid: 47206
[21:55:07] [nodemon] watching 140 files
Now start API server on port 3000...
Now start WebSocket server on port 3001...

**Comment by ghost** [comment]
能不能出个json格式的接口文档。准备用java 提供后台 前后端分离权限控制

**Comment by wjkang** [comment]
> 
> 
> 能不能出个json格式的接口文档。准备用java 提供后台 前后端分离权限控制

抱歉，暂时没有时间整理，你可以F12看网络请求，接口也不多

**Comment by wjkang** [comment]
> 
> 
> "dependencies" has dependency "shortid" with range "^2.2.13" that collides with a dependency in "devDependencies" of the same name with version "^2.2.8".
> package.json 中的 dependencies 和 devDependencies均有一个依赖叫 shorid。

@qhj1990  
![default](https://user-images.githubusercontent.com/9456046/53816573-b96fb800-3f9e-11e9-8221-3dd23c2772eb.png)
我本地的环境，没有问题，你可以把低版本的去掉试试
